FROM php:7.4-apache

# Additional packages
RUN apt-get update \
    && apt-get install --yes --no-install-recommends libzip-dev \
    zip \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install mysqli \
    && docker-php-ext-install zip


# Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Enable rewrite mode on Apache
RUN a2enmod rewrite